package app.gui;

import app.service.ReserveService;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import app.dto.ReserveDTO;
import app.model.Reserve;
import javax.swing.JOptionPane;

public class ReserveRegister extends javax.swing.JFrame {

    private ReserveService reserveService = new ReserveService();

    public ReserveRegister() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setPaymentMethods();
        this.inputCheckIn.setDate(new Date());
        this.inputCheckOut.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        paymentMethods = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        calculateValue = new javax.swing.JButton();
        inputCheckIn = new com.toedter.calendar.JDateChooser();
        inputCheckOut = new com.toedter.calendar.JDateChooser();
        BtnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img-registroReservas.png"))); // NOI18N

        btnReturn.setBackground(new java.awt.Color(51, 153, 255));
        btnReturn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("<");
        btnReturn.setFocusable(false);
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 140, 198));
        jLabel2.setText("SISTEMA DE RESERVAS");

        txtMoney.setEditable(false);
        txtMoney.setBackground(new java.awt.Color(255, 255, 255));
        txtMoney.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMoney.setForeground(new java.awt.Color(51, 51, 51));
        txtMoney.setText("$");
        txtMoney.setBorder(null);
        txtMoney.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        paymentMethods.setBackground(new java.awt.Color(255, 255, 255));
        paymentMethods.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        paymentMethods.setForeground(new java.awt.Color(51, 51, 51));
        paymentMethods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("VALOR DE LA RESERVA");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("FECHA DE CHECK IN");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("FECHA DE CHECK OUT");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("FORMA DE PAGO");

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));

        calculateValue.setBackground(new java.awt.Color(17, 140, 198));
        calculateValue.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        calculateValue.setForeground(new java.awt.Color(255, 255, 255));
        calculateValue.setText("Calcular valor");
        calculateValue.setFocusable(false);
        calculateValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateValueMouseClicked(evt);
            }
        });

        inputCheckIn.setDateFormatString("yyyy-MM-dd");
        inputCheckIn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                inputCheckInAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        inputCheckIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                inputCheckInPropertyChange(evt);
            }
        });

        inputCheckOut.setDateFormatString("yyyy-MM-dd");
        inputCheckOut.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                inputCheckOutComponentAdded(evt);
            }
        });
        inputCheckOut.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputCheckOutInputMethodTextChanged(evt);
            }
        });
        inputCheckOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                inputCheckOutPropertyChange(evt);
            }
        });

        BtnNext.setBackground(new java.awt.Color(17, 140, 198));
        BtnNext.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        BtnNext.setForeground(new java.awt.Color(255, 255, 255));
        BtnNext.setText("Siguiente");
        BtnNext.setFocusable(false);
        BtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inputCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paymentMethods, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMoney)
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator4)
                        .addComponent(inputCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateValue)
                .addGap(18, 18, 18)
                .addComponent(BtnNext)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentMethods, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateValue)
                    .addComponent(BtnNext))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnReturn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        //Se instancia User Menu
        UserMenu userMenu = new UserMenu();
        //Se oculta la ventana actual
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnMouseClicked

    private void inputCheckInAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_inputCheckInAncestorAdded

    }//GEN-LAST:event_inputCheckInAncestorAdded

    //Método utilizado para setear el precio de la reserva, teniendo en cuetna las fechas
    private void inputCheckOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_inputCheckOutPropertyChange

    }//GEN-LAST:event_inputCheckOutPropertyChange

    private void inputCheckOutComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_inputCheckOutComponentAdded

    }//GEN-LAST:event_inputCheckOutComponentAdded

    private void inputCheckOutInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputCheckOutInputMethodTextChanged

    }//GEN-LAST:event_inputCheckOutInputMethodTextChanged

    private void inputCheckInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_inputCheckInPropertyChange

    }//GEN-LAST:event_inputCheckInPropertyChange

    //Método encargado de calcular el valor de la reserva y seteralo en el campo
    private void calculateValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateValueMouseClicked
        //Obtención de datos
        Calendar calendarCheckIn = this.inputCheckIn.getCalendar();
        Calendar calendarCheckOut = this.inputCheckOut.getCalendar();
        Date dateCheckIn = calendarCheckIn.getTime();
        Date dateCheckOut = calendarCheckOut.getTime();
            //Llamado al método encargado de calcular el valor
            Double value = calculateValue();
            //Se setea el valor en campo de texto
            this.txtMoney.setText(String.valueOf(value).concat(" USD"));
     

    }//GEN-LAST:event_calculateValueMouseClicked

    private void BtnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNextMouseClicked
       //Obtención de datos seleccionados para la creacion de la reserva
        Date entryDate = this.inputCheckIn.getDate();
       Date departureDate = this.inputCheckOut.getDate();
       Double value=calculateValue();
       if(value!=0.0){
           String paymentMethod = paymentMethods.getSelectedItem().toString();
       //Llamado al método encargado de la manipulacion de los datos y asi crear la reserva
       Reserve reserveCreated= (Reserve) this.reserveService.create(
                new ReserveDTO
        (entryDate,departureDate,value,paymentMethod));
       //Generacion de numero de reserva
       Integer reservationNumber = (int)(Math.random()*10+1)*10;
       //Se le muestra al usuario el número de reserva
      JOptionPane.showMessageDialog(
                    null,
                    "Número de reserva: "+reservationNumber,
                    "Message",
                    JOptionPane.INFORMATION_MESSAGE);
       //Instancia de la clase de registro de un huesped
       GuestRegistration guestRegistration=
               new GuestRegistration(
                       reservationNumber,
                       reserveCreated.getId());
       //Ocultacion de la ventana actual
       this.setVisible(false);
       }
       
    }//GEN-LAST:event_BtnNextMouseClicked
//Método para definir el modelo en el select de metodos de pago

    private void setPaymentMethods() {
        String[] methods
                = {"Tarjeta de crédito", "Tarjeta de débito", "Dinero en efectivo"};
        ComboBoxModel model = new DefaultComboBoxModel(methods);
        this.paymentMethods.setModel(model);
    }

  private Double calculateValue() {
        Date entryDate = this.inputCheckIn.getDate();
       Date departureDate = this.inputCheckOut.getDate();
       Double reserveValue=0.0;
       //Verificación de entrada de datos
        boolean verify = this.reserveService.verifyData(entryDate, departureDate);
        if(verify){  
            reserveValue =
                    this.reserveService
                            .calculateValue(entryDate, departureDate);}
        return reserveValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton calculateValue;
    private com.toedter.calendar.JDateChooser inputCheckIn;
    private com.toedter.calendar.JDateChooser inputCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> paymentMethods;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
